CREATE TABLE IF NOT EXISTS user (id TEXT NOT NULL PRIMARY KEY,email TEXT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS session (
    id TEXT NOT NULL PRIMARY KEY,
    expires_at INTEGER NOT NULL,
    user_id TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
